# Generated by Django 4.2.6 on 2024-01-01 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0067_sale_returnmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('action', models.CharField(blank=True, choices=[('defective', 'Defective'), ('no_action', 'No action')], max_length=20, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.category')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.itemsmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='sale_returnModel',
        ),
    ]
