# Generated by Django 4.2.6 on 2024-01-01 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0068_salesreturn_delete_sale_returnmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturn',
            name='batch_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.stock'),
        ),
    ]
