# Generated by Django 4.2.6 on 2024-01-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0069_alter_salesreturn_batch_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturn',
            name='action',
        ),
    ]
