# Generated by Django 4.2.6 on 2024-01-07 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0070_remove_salesreturn_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectiveitem',
            name='stock',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.stock'),
            preserve_default=False,
        ),
    ]
