# Generated by Django 4.2.6 on 2024-01-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0073_remove_product_name_product_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
    ]
