# Generated by Django 4.2.6 on 2024-01-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0075_account_pay_remove_stock_account_payable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account_pay',
            new_name='Account_payableModel',
        ),
    ]
