# Generated by Django 4.2.6 on 2024-01-10 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0076_rename_account_pay_account_payablemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_payablemodel',
            name='vender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmgmt.vender'),
        ),
    ]
